# Настройки приложения CatchCam
# HANDS: Включить/выключить детектор рук (true/false)
HANDS: true

# FACE: Настройки детектора лица
FACE:
  # turn_on: Включить Face Mesh (сетку лица)
  turn_on: false
  # draw_face: Рисовать ли сетку на лице
  draw_face: true

# FPS_IMG: Показывать счетчик кадров в секунду (true/false)
FPS_IMG: true

# DIFFICULTY: Сложность игр (1-5)
DIFFICULTY: 3

# BG: Настройки удаления/замены фона
BG:
  # turn_on: Включить сегментацию (True убирает фон)
  turn_on: false
  # threshold: Чувствительность отделения фона (от 0 до 1)
  threshold: 0.5
  # COLOR: Цвет фона в формате BGR, если картинка не задана
  COLOR: [255, 0, 0]
  # img: Ссылка на изображение в интернете или локальный путь для фона
  img: ""
